controller:
  admin:
    createSecret: true

  serviceType: LoadBalancer

  installPlugins:
    - kubernetes
    - workflow-aggregator
    - git
    - configuration-as-code
    - credentials-binding

  persistence:
    enabled: true
    size: 10Gi

  serviceAccount:
    create: true
    name: jenkins-sa
    annotations:
      eks.amazonaws.com/role-arn: "arn:aws:iam::889951087627:role/jenkins-role"

  resources:
    requests:
      cpu: "500m"
      memory: "1Gi"

    limits:
      cpu: "1000m"
      memory: "2Gi"

agent:
  enabled: true
