apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  DEBUG: {{ .Values.env.debugMode | quote }}
  ALLOWED_HOSTS: {{ .Values.env.allowedHosts | quote }}
  DB_HOST: {{ .Values.env.dbHost | quote }}
  DB_NAME: {{ .Values.env.dbName | quote }}
  DB_USER: {{ .Values.env.dbUser | quote }}
  DB_PORT: {{ .Values.env.dbPort | quote }}
