apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
data:
  DB_HOST: {{ .Values.env.dbHost | quote }}
  DB_NAME: {{ .Values.env.dbName | quote }}
  DB_USER: {{ .Values.env.dbUser | quote }}
  DB_PASSWORD: {{ .Values.env.dbPassword | quote }}
  DEBUG: {{ .Values.env.debugMode | quote }}
