replicaCount: 2

image:
  repository: "" # Set via: helm upgrade --install ... --set image.repository=<account>.dkr.ecr.us-west-2.amazonaws.com/lesson-5-ecr
  tag: "latest"
  pullPolicy: IfNotPresent

service:
  type: LoadBalancer
  port: 80
  targetPort: 8000

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 200m
    memory: 256Mi

hpa:
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70

# Открытые конфигурации
env:
  debugMode: "False"
  allowedHosts: "*"
  dbHost: "postgres-service"
  dbName: "django_prod"
  dbUser: "django_user"
  dbPort: "5432"

# Секретные данные (будут зашифрованы в Kubernetes Secret)
secrets:
  secretKey: "djanog-super-safe-secret-key-12345"
  dbPassword: "highly-secure-database-password-2026"

ingress:
  enabled: false
  className: "nginx"
  host: "yourdomain.com"
  path: /
  pathType: Prefix
  tls: true
