apiVersion: v1
kind: Secret

metadata:
  name: github-repository

  labels:
    argocd.argoproj.io/secret-type: repository

stringData:
  type: git

  url: https://github.com/anastasiia-kushch/my-microservice-project.git
